# Generated by Django 4.2.5 on 2023-09-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=15)),
                ("hireDate", models.DateField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
